
import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'en' | 'am';

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.products': 'Products',
    'nav.returns': 'Returns & Damages',
    'nav.credits': 'Credits',
    'nav.reports': 'Reports',
    'nav.analysis': 'Analysis',
    'nav.payments': 'Payments',
    'nav.buyers': 'Buyers',
    'nav.pricing': 'Pricing',
    'nav.staff': 'Staff',
    'nav.roles': 'Roles',
    'nav.logs': 'System Logs',
    'nav.settings': 'Settings',
    'nav.catalog': 'Catalog & Ordering',
    'nav.history': 'Order History',
    'nav.financials': 'Credit & Financials',
    
    // Header Titles (Dynamic)
    'header.dashboard': 'Dashboard',
    'header.returns': 'Returns & Damage Analysis',
    'header.orders': 'Orders',
    'header.products': 'Products Catalog',
    'header.buyers': 'Wholesale Buyers',
    'header.payments': 'Payments',
    'header.staff': 'Team Management',
    'header.roles': 'Permission Roles',
    'header.pricing': 'Pricing Strategy',
    'header.reports': 'Reports',
    'header.analytics': 'Analysis',
    'header.settings': 'Settings',
    'header.logReturn': 'Log New Incident',
    'header.creditMgmt': 'Credit Management',
    'header.logCredit': 'Issue Credit Note',
    'header.createOrder': 'Create Order',
    'header.processOrder': 'Process Order',
    'header.orderDetails': 'Order Details',
    'header.addProduct': 'Register Product',
    'header.restock': 'Restock Inventory',
    'header.productDetails': 'Product Details',
    'header.addBuyer': 'Register Buyer',
    'header.buyerProfile': 'Buyer Profile',
    'header.addStaff': 'Invite Staff',
    'header.staffProfile': 'Staff Profile',
    'header.addRole': 'New Role Profile',
    'header.roleConfig': 'Role Configuration',
    'header.addPricing': 'New Pricing Tier',
    'header.bulkConfig': 'Bulk Volume Configuration',
    'header.marginConfig': 'Profit Protection Rule',
    'header.tierConfig': 'Tier Configuration',
    'header.reviewPayment': 'Review Payment',
    'header.alerts': 'Low Stock Alerts',
    'header.logs': 'System Audit Logs',

    // Dashboard
    'dash.hello': 'Hello',
    'dash.invValue': 'Inv. Value',
    'dash.totalSkus': 'Total SKUs',
    'dash.onOrder': 'On Order',
    'dash.sellThrough': 'Sell-Through',
    'dash.alerts': 'Inventory Alerts',
    'dash.alertsDesc': 'Action required for products that are critically low.',
    'dash.action': 'Take Action',
    'dash.distribution': 'Distribution',
    'dash.pulse': 'Operational Pulse',
    'dash.viewAll': 'View All',
    'dash.stockCapacity': 'Stock Capacity',
    'dash.newOrder': 'New Order',
    'dash.lastMonth': 'from last month',
    
    // Settings
    'settings.title': 'Settings & Preferences',
    'settings.subtitle': 'Customize your application experience.',
    'settings.localization': 'Localization',
    'settings.language': 'Display Language',
    'settings.notifications': 'Notifications',
    'settings.emailAlerts': 'Email Alerts',
    'settings.emailDesc': 'Receive daily summaries and critical alerts.',
    'settings.pushNotifs': 'Push Notifications',
    'settings.pushDesc': 'Real-time browser notifications for orders.',
    'settings.security': 'Security',
    'settings.password': 'Password',
    'settings.lastChanged': 'Last changed 3 months ago',
    'settings.changePwd': 'Change Password',
    'settings.categories': 'Product Categories',
    'settings.newCategory': 'New Category',
    'settings.categoryName': 'Category Name',
    'settings.manageCategories': 'Manage Product Filters',
    'settings.categoryInUse': 'Cannot delete or edit: This category is currently assigned to products.',
    
    // Auth & Login
    'auth.welcome': 'Welcome to B2B Intel',
    'auth.selectType': 'Select your account type to continue',
    'auth.buyer': 'Wholesale Buyer',
    'auth.buyerDesc': 'Retail partners looking to browse products, place wholesale orders, and track shipments.',
    'auth.buyerLogin': 'Buyer Login',
    'auth.seller': 'Seller & Staff',
    'auth.sellerDesc': 'Internal team members, warehouse managers, and admins managing operations.',
    'auth.staffLogin': 'Staff Login',
    'auth.secure': 'Secure Access Point',
    'login.sellerTitle': 'Seller & Staff Portal',
    'login.sellerSubtitle': 'Secure access for inventory management and order processing',
    'login.staffIdLabel': 'Staff ID or Email',
    'login.password': 'Password',
    'login.forgot': 'Forgot Password?',
    'login.signIn': 'Sign In',
    'login.authenticating': 'Authenticating...',
    'login.needAccess': 'Need system access?',
    'login.contactAdmin': 'Contact Admin',
    'login.switch': 'Switch Account Type',
    'login.buyerTitle': 'Retail Partner Login',
    'login.buyerSubtitle': 'Access your wholesale dashboard for viewing products and placing orders',
    'login.buyerIdLabel': 'Buyer ID or Email',
    'login.trouble': 'Having trouble logging in?',
    'login.faq': 'FAQ',
    'login.support': 'Support',

    // Buyer Dashboard
    'buyer.welcome': 'Welcome back',
    'buyer.overview': 'Overview',
    'buyer.activeOrders': 'Active Orders',
    'buyer.loyaltyTier': 'Loyalty Tier',
    'buyer.monthlyOrders': 'Monthly Orders',
    'buyer.monthlySpend': 'Monthly Spend',
    'buyer.totalSpend': 'Total Spend',
    'buyer.recentOrders': 'Recent Orders',
    'buyer.viewHistory': 'View All History',
    'buyer.recommended': 'Recommended for You',
    'buyer.seeAll': 'See All Products',
    'buyer.add': 'Add',
    'buyer.noOrders': 'No orders yet',

    // Buyer Common
    'buyer.cart': 'Cart',
    'buyer.items': 'Items',
    'buyer.subtotal': 'Subtotal',
    'buyer.tax': 'Tax',
    'buyer.total': 'Total',
    'buyer.placeOrder': 'Place Order',
    'buyer.saveDraft': 'Save as Draft',
    'buyer.search': 'Search products...',
    'buyer.soldOut': 'Sold Out',
    'buyer.lowStock': 'Low Stock',
    'buyer.inStock': 'In Stock',
    'buyer.pay': 'Pay',
    'buyer.invoice': 'Invoice',
    'buyer.makePayment': 'Make Payment',
    'buyer.requestCredit': 'Request Credit',
    'buyer.reorder': 'Reorder',
    'buyer.cancelOrder': 'Cancel Order',
    'buyer.deleteOrder': 'Delete Order',
    'buyer.editDraft': 'Edit Draft',
    'buyer.notifications': 'Notifications',

    // Orders Management
    'status.all': 'All Orders',
    'status.draft': 'Draft',
    'status.on_review': 'On Review',
    'status.pending': 'Pending',
    'status.processing': 'Processing',
    'status.shipped': 'Shipped',
    'status.delivered': 'Delivered',
    'status.undelivered': 'Undelivered',
    'status.cancelled': 'Cancelled',
    'status.deleted': 'Deleted',
    'order.new': 'New Order',
    'order.process': 'Process',
    'order.verify': 'Verify',
    'order.submit': 'Submit',
    'order.fulfill': 'Fulfill Order',
    'order.markDelivered': 'Mark Delivered',
    'order.lifecycle': 'Order Life-cycle',
    'order.partner': 'Purchasing Partner',
    'order.manifest': 'Manifest Items',
    'order.timeline': 'Audit Timeline',
    'order.cancel': 'Cancel',
    'order.invoice': 'Invoice',
    'order.edit': 'Edit Order',
    'order.undelivered': 'Undelivered',
    'order.wholesaleValue': 'Wholesale Value',
    'order.notFound': 'Order not found.',
    'order.cancelledBySeller': 'Seller cancelled',
    'order.confirmedDelivered': 'Order confirmed delivered by field staff',
    'order.deliveryConfirmMessage': 'This will update the order status to Delivered. Ensure the buyer has received all items in good condition.',
    'order.stockRestock': 'Stock to be Restocked:',
    'order.autoRestock': 'Stock will be restocked automatically',
    'order.stopFulfillment': 'Stops fulfillment process',
    'order.softDelete': 'Soft-Deletion Protocol',
    'order.confirmHandover': 'Confirm successful handover',
    
    // Products Management
    'cat.all': 'All',
    'loc.all': 'All Locations',
    'loc.warehouse': 'Warehouse',
    'loc.backroom': 'Back Room',
    'loc.showroom': 'Show Room',
    'prod.add': 'Add SKU',
    'prod.restock': 'Restock',
    'prod.editMode': 'Edit Mode',
    'prod.discard': 'Discard',
    'prod.saveChanges': 'Save Catalog Changes',
    'prod.delete': 'Delete Product',
    'prod.modify': 'Modify Product',
    'prod.restockUnits': 'Restock Units',
    'prod.fulfillmentStock': 'Fulfillment Stock',
    'prod.catalogAttributes': 'Catalog Attributes',
    'prod.brand': 'Brand',
    'prod.category': 'Category',
    'prod.cost': 'Cost Price',
    'prod.sellingPrice': 'Selling Price',
    'prod.description': 'Product Description',
    'prod.reorderPoint': 'Reorder Point',
    'prod.status': 'Lifecycle Status',
    'prod.wholesale': 'Wholesale',
    'prod.units': 'Units',
    'prod.noMatch': 'No matching products found',
    'prod.notFound': 'Product not found',
    'prod.updated': 'Product catalog updated successfully.',
    'prod.deleteConfirm': 'Are you sure you want to permanently delete',
    'prod.supplierName': 'Supplier Name',
    'prod.supplierPhone': 'Supplier Phone',

    // Common Actions & Labels
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.confirm': 'Confirm',
    'common.view': 'View',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.search': 'Search...',
    'logout': 'Logout',
    'common.id': 'ID',
    'common.buyer': 'Buyer',
    'common.revenue': 'Revenue',
    'common.accountId': 'Account ID',
    'common.sku': 'SKU',
    'common.loading': 'Loading...',
    'common.upload': 'Upload',
    'common.reasonRequired': 'Please provide a reason.',
    'common.deletionReason': 'Reason for Deletion',
    'common.cancellationReason': 'Cancellation Reason',
    'common.deliveryFailureReason': 'Delivery Failure Reason',
    'common.internalNotes': 'Internal Notes',
    'common.actions': 'Actions',
    'common.noRecords': 'No records found',
    'common.discardChanges': 'Discard Changes',
    'common.saveUpdates': 'Save Updates',
    'common.activate': 'Activate',
    'common.deactivate': 'Deactivate',
    'common.editProfile': 'Edit Profile',
    'common.cancelEdit': 'Cancel Edit',
    'common.item': 'Item',
    'common.type': 'Type',
    'common.quantity': 'Quantity',
    'common.reason': 'Reason',
    'common.resolution': 'Resolution',

    // Analytics
    'reports.title': 'Reports',
    'reports.subtitle': 'Performance snapshots for your wholesale operation',
    'reports.revenueTrend': 'Revenue Performance',
    'reports.revenueTrendDesc': 'Revenue trend based on available order history.',
    'reports.topTrendsDesc': 'Best-performing products in the latest comparison window.',
    'analytics.title': 'Analysis',
    'analytics.subtitle': 'Forecasting and scenario exploration for wholesale demand',
    'analytics.viewScope': 'View Scope',
    'analytics.salesGrowth': 'Sales Growth',
    'analytics.vsPrevious': 'vs. previous',
    'analytics.totalRevenue': 'Total Revenue',
    'analytics.allTime': 'All Time',
    'analytics.inventoryTurnover': 'Inventory Turnover',
    'analytics.efficiencyScore': 'Efficiency Score',
    'analytics.demandForecast': 'Demand Forecast',
    'analytics.historical': 'Historical',
    'analytics.forecasted': 'Forecasted',
    'analytics.scenarioTitle': 'Scenario Modeling',
    'analytics.scenarioDesc': 'Upload external sales data (CSV) to run forecasting models.',
    'analytics.uploadCsv': 'Upload CSV',
    'analytics.changeFile': 'Change File',
    'analytics.clearData': 'Clear Data',
    'analytics.dropCsv': 'Drop CSV File Here',
    'analytics.csvFormat': 'Format: Date (Column 1), Sales Value (Column 2)',
    'analytics.topTrends': 'Top Product Trends',
    'analytics.recentVsPrev': 'Recent vs Previous',
    'analytics.noData': 'No sales data available.',
    'analytics.lastMonth': 'from last month',

    // Returns
    'returns.financialImpact': 'Financial Impact',
    'returns.financialImpactDesc': 'Value lost through damages & disposal',
    'returns.operationalPulse': 'Operational Pulse',
    'returns.operationalPulseDesc': 'Incidents recorded this month',
    'returns.recoveryRate': 'Recovery Rate',
    'returns.recoveryRateDesc': 'Percentage of goods returned to inventory',
    'returns.reasonDistribution': 'Incident Reason Distribution',
    'returns.recentLog': 'Recent Incident Log',
    'returns.addLog': 'Add Log',
    'returns.noIncidents': 'No incidents logged',
    'returns.supplierWatch': 'Supplier Pattern Watch',
    'returns.riskScore': 'Risk Score',
    'returns.packagingFault': 'Packaging Fault Pattern Detected',
    'returns.globalPattern': 'Global Pattern Detection',
    'returns.logTitle': 'Log Product Incident',
    'returns.logDesc': 'Record damage or customer returns.',
    'returns.itemInfo': 'Item Information',
    'returns.selectProduct': 'Select Catalog Product',
    'returns.chooseProduct': 'Choose product...',
    'returns.incidentType': 'Incident Type',
    'returns.unitsAffected': 'Units Affected',
    'returns.triggerReason': 'Trigger Reason',
    'returns.fulfillmentRes': 'Fulfillment Resolution',
    'returns.resRestock': 'Restock to Main Warehouse',
    'returns.resDisposal': 'Mark for Disposal (Loss)',
    'returns.resReturn': 'Return to Manufacturer',
    'returns.completeLog': 'Complete Incident Log',

    // Credits
    'credits.title': 'Credit Management',
    'credits.subtitle': 'Review refund requests and issue credit notes.',
    'credits.logRequest': 'Log Credit Request',
    'credits.pendingApproval': 'Pending Approval',
    'credits.creditsIssued': 'Credits Issued (Total)',
    'credits.reqId': 'Request ID',
    'credits.assocOrder': 'Associated Order',
    'credits.requested': 'Requested',
    'credits.approved': 'Approved',
    'credits.generalCredit': 'General Credit',
    'credits.noRequests': 'No credit requests found',
    'credits.logTitle': 'Issue Credit Note',
    'credits.logDesc': 'Log a request for a refund or account credit.',
    'credits.accountDetails': 'Account Details',
    'credits.selectBuyer': 'Select Buyer Account',
    'credits.chooseBuyer': 'Choose buyer...',
    'credits.assocOrderOpt': 'Associated Order (Optional)',
    'credits.generalCreditOpt': 'General Credit (No specific order)',
    'credits.creditTerms': 'Credit Terms',
    'credits.creditAmount': 'Credit Amount (ETB)',
    'credits.reasonCode': 'Reason Code',
    'credits.notesPlaceholder': 'Details for approval...',
    'credits.submitRequest': 'Submit Request',

    // Payments
    'payments.title': 'Payments',
    'payments.proof': 'Proof of Payment',
    'payments.viewProof': 'View Full Image',
    'payments.verification': 'Verification Details',
    'payments.expected': 'Expected Amount',
    'payments.reported': 'Reported Amount',
    'payments.reference': 'Reference ID',
    'payments.submissionTime': 'Submission Time',
    'payments.mismatch': 'Amount Mismatch',
    'payments.mismatchDesc': 'The reported payment amount does not match the total order value. Please verify before approving.',
    'payments.reviewNotes': 'Review Notes',
    'payments.reviewNotesPlaceholder': 'Add a reason for rejection or special notes...',
    'payments.reject': 'Reject',
    'payments.markMismatch': 'Mismatch',
    'payments.approve': 'Approve',
    'payments.noPayments': 'No payments found for this filter',
    'status.pending_review': 'Pending Review',
    'status.approved': 'Approved',
    'status.rejected': 'Rejected',
    'status.mismatched': 'Mismatched',

    // Alerts
    'alerts.title': 'Low Stock Alerts',
    'alerts.subtitle': 'Items that require immediate restocking attention.',
    'alerts.bulkRestock': 'Bulk Restock',
    'alerts.quickRestock': 'Quick Restock',
    'alerts.allStocked': 'All Stocked Up!',
    'alerts.allStockedDesc': 'There are currently no products flagged with low stock levels.',
    'alerts.browseCatalog': 'Browse Catalog',

    // Buyers
    'buyers.title': 'Wholesale Partners',
    'buyers.subtitle': 'Accounts Registered',
    'buyers.newBuyer': 'New Buyer',
    'buyers.searchPlaceholder': 'Search accounts by name, ID or contact...',
    'buyers.perk': 'Perk',
    'buyers.noMatch': 'No accounts match your search',
    'buyers.notFound': 'Buyer not found.',
    'buyers.member': 'Member',
    'buyers.lifetimeSpend': 'Lifetime Spend',
    'buyers.orderCount': 'Order Count',
    'buyers.pricingPerk': 'Pricing Perk',
    'buyers.accountState': 'Account State',
    'buyers.modifyIdentity': 'Modify Identity',
    'buyers.businessInfo': 'Business Information',
    'buyers.companyName': 'Company Legal Name',
    'buyers.contactManager': 'Contact Manager',
    'buyers.businessPhone': 'Business Phone',
    'buyers.primaryEmail': 'Primary Email Address',
    'buyers.deliveryPoint': 'Main Delivery Point',
    'buyers.legalName': 'Legal Entity Name',
    'buyers.primaryContact': 'Primary Point of Contact',
    'buyers.businessEmail': 'Business Email Address',
    'buyers.regPhone': 'Registered Phone',
    'buyers.fulfillmentTerminal': 'Fulfillment Terminal',
    'buyers.partnerTier': 'Partner Tier & Benefits',
    'buyers.off': 'Off',
    'buyers.operationalLog': 'Operational Log',
    'buyers.fullHistory': 'Full History',

    // Logs
    'logs.title': 'System Audit Log',
    'logs.eventsRecorded': 'events recorded',
    'logs.refresh': 'Refresh Logs',
    'logs.searchPlaceholder': 'Search logs by action, user, or details...',
    'logs.noLogs': 'No logs match your criteria',
    'log.module.all': 'All',
    'log.module.orders': 'Orders',
    'log.module.inventory': 'Inventory',
    'log.module.finance': 'Finance',
    'log.module.users': 'Users',
    'log.module.settings': 'Settings',

    // Pricing
    'pricing.title': 'Pricing Strategy',
    'pricing.subtitle': 'Multi-layered Discount Engine',
    'pricing.newTier': 'New Tier',
    'pricing.newVolume': 'Volume Step',
    'pricing.newConstraint': 'Constraint',
    'pricing.tiers': 'Loyalty Tiers',
    'pricing.bulk': 'Bulk Volume',
    'pricing.margin': 'Profit Protection',
    'pricing.gifted': 'Gifted upon reaching targets',
    'pricing.minSpend': 'Spend',
    'pricing.tenure': 'Tenure',
    'pricing.bulkTitle': 'Global Volume Thresholds',
    'pricing.bulkDesc': 'Automatic per-item discounts when unit counts are met.',
    'pricing.newVolumeStep': 'Define New Volume Step',
    'pricing.marginTitle': 'Profit Guard Logic',
    'pricing.marginDesc': 'Automatically incentivize high-margin items. If a product\'s unit cost and your revenue margin meet these criteria, an additional discount is granted to the buyer.',
    'pricing.trigger': 'Trigger Condition',
    'pricing.incentive': 'Incentive',
    'pricing.addConstraint': 'Add Constraint',
    'pricing.bonus': 'Bonus',

    // Staff
    'staff.title': 'Team Members',
    'staff.activeAccounts': 'Active Accounts',
    'staff.newStaff': 'New Staff',
    'staff.search': 'Search team members by name, role or email...',
    'staff.noMatch': 'No team members match your search',

    // Roles
    'roles.title': 'Permission Roles',
    'roles.profiles': 'Access Profiles',
    'roles.new': 'New Role',
    'roles.search': 'Search roles by name, level or capability...',
    'roles.members': 'Members',
    'roles.activeModules': 'Active Modules',
    'roles.globalScope': 'Global Scope',
    'roles.systemWide': 'System-Wide',
    'roles.restricted': 'Restricted',
    'roles.noMatch': 'No roles match your search',
    'roles.more': 'More',
  },
  am: {
    // Navigation
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.orders': 'ትዕዛዞች',
    'nav.products': 'ምርቶች',
    'nav.returns': 'ተመላሾች እና ጉዳቶች',
    'nav.credits': 'ብድሮች',
    'nav.reports': 'ሪፖርቶች',
    'nav.analysis': 'ትንተና',
    'nav.payments': 'ክፍያዎች',
    'nav.buyers': 'ገዢዎች',
    'nav.pricing': 'ዋጋ አሰጣጥ',
    'nav.staff': 'ሰራተኞች',
    'nav.roles': 'ሚናዎች',
    'nav.logs': 'የሲስተም መዝገቦች',
    'nav.settings': 'ቅንብሮች',
    'nav.catalog': 'ካታሎግ እና ማዘዣ',
    'nav.history': 'የትዕዛዝ ታሪክ',
    'nav.financials': 'ፋይናንስ እና ብድር',

    // Header Titles (Dynamic)
    'header.dashboard': 'ዳሽቦርድ',
    'header.returns': 'የተመላሾች እና ጉዳት ትንተና',
    'header.orders': 'ትዕዛዞች',
    'header.products': 'የምርት ካታሎግ',
    'header.buyers': 'የጅምላ ገዢዎች',
    'header.payments': 'ክፍያዎች',
    'header.staff': 'የቡድን አስተዳደር',
    'header.roles': 'የፍቃድ ሚናዎች',
    'header.pricing': 'የዋጋ ስትራቴጂ',
    'header.reports': 'ሪፖርቶች',
    'header.analytics': 'ትንተና',
    'header.settings': 'ቅንብሮች',
    'header.logReturn': 'አዲስ ክስተት ይመዝግቡ',
    'header.creditMgmt': 'የብድር አስተዳደር',
    'header.logCredit': 'የብድር ማስታወሻ ይስጡ',
    'header.createOrder': 'ትዕዛዝ ይፍጠሩ',
    'header.processOrder': 'ትዕዛዝ ያቀናብሩ',
    'header.orderDetails': 'የትዕዛዝ ዝርዝሮች',
    'header.addProduct': 'ምርት ይመዝግቡ',
    'header.restock': 'ክምችት ሙላ',
    'header.productDetails': 'የምርት ዝርዝሮች',
    'header.addBuyer': 'ገዢ ይመዝግቡ',
    'header.buyerProfile': 'የገዢ መገለጫ',
    'header.addStaff': 'ሰራተኛ ይጋብዙ',
    'header.staffProfile': 'የሰራተኛ መገለጫ',
    'header.addRole': 'አዲስ ሚና መገለጫ',
    'header.roleConfig': 'የሚና ውቅር',
    'header.addPricing': 'አዲስ የዋጋ ደረጃ',
    'header.bulkConfig': 'የጅምላ ብዛት ውቅር',
    'header.marginConfig': 'የትርፍ ጥበቃ ደንብ',
    'header.tierConfig': 'የደረጃ ውቅር',
    'header.reviewPayment': 'ክፍያ ይገምግሙ',
    'header.alerts': 'ዝቅተኛ ክምችት ማስጠንቀቂያዎች',
    'header.logs': 'የሲስተም ኦዲት መዝገቦች',

    // Dashboard
    'dash.hello': 'ሰላም',
    'dash.invValue': 'የክምችት ዋጋ',
    'dash.totalSkus': 'ጠቅላላ ዓይነቶች',
    'dash.onOrder': 'በሂደት ላይ ያለ',
    'dash.sellThrough': 'የሽያጭ መጠን',
    'dash.alerts': 'የክምችት ማስጠንቀቂያዎች',
    'dash.alertsDesc': 'በጣም ዝቅተኛ ለሆኑ ምርቶች እርምጃ ያስፈልጋል።',
    'dash.action': 'እርምጃ ይውሰዱ',
    'dash.distribution': 'ስርጭት',
    'dash.pulse': 'የአሰራር እንቅስቃሴ',
    'dash.viewAll': 'ሁሉንም ይመልከቱ',
    'dash.stockCapacity': 'የክምችት አቅም',
    'dash.newOrder': 'አዲስ ትዕዛዝ',
    'dash.lastMonth': 'ካለፈው ወር',

    // Settings
    'settings.title': 'ቅንብሮች እና ምርጫዎች',
    'settings.subtitle': 'የመተግበሪያዎን ተሞክሮ ያብጁ።',
    'settings.localization': 'ቋንቋ',
    'settings.language': 'የማሳያ ቋንቋ',
    'settings.notifications': 'ማሳወቂያዎች',
    'settings.emailAlerts': 'የኢሜይል ማስጠንቀቂያዎች',
    'settings.emailDesc': 'ዕለታዊ ማጠቃለያዎችን እና ወሳኝ ማስጠንቀቂያዎችን ይቀበሉ።',
    'settings.pushNotifs': 'የግፊት ማሳወቂያዎች',
    'settings.pushDesc': 'ለአዳዲስ ትዕዛዞች ፈጣን ማሳወቂያዎች።',
    'settings.security': 'ደህንነት',
    'settings.password': 'የይለፍ ቃል',
    'settings.lastChanged': 'ከ 3 ወራት በፊት ተቀይሯል',
    'settings.changePwd': 'የይለፍ ቃል ይቀይሩ',
    'settings.categories': 'የምርት ምድቦች',
    'settings.newCategory': 'አዲስ ምድብ',
    'settings.categoryName': 'የምድብ ስም',
    'settings.manageCategories': 'የምርት ማጣሪያዎችን ያቀናብሩ',
    'settings.categoryInUse': 'መሰረዝ ወይም ማስተካከል አይቻልም፡ ይህ ምድብ በአሁኑ ጊዜ ለምርቶች ተሰጥቷል።',

    // Auth & Login
    'auth.welcome': 'ወደ B2B Intel እንኳን በደህና መጡ',
    'auth.selectType': 'ለመቀጠል የሂሳብ አይነትዎን ይምረጡ',
    'auth.buyer': 'የጅምላ ገዢ',
    'auth.buyerDesc': 'ምርቶችን ለማየት፣ የጅምላ ትዕዛዞችን ለመላክ እና ጭነት ለመከታተል።',
    'auth.buyerLogin': 'የገዢ መግቢያ',
    'auth.seller': 'ሻጭ እና ሰራተኞች',
    'auth.sellerDesc': 'ለውስጥ ቡድን አባላት፣ የመጋዘን አስተዳዳሪዎች እና አስተዳዳሪዎች።',
    'auth.staffLogin': 'የሰራተኞች መግቢያ',
    'auth.secure': 'ደህንነቱ የተጠበቀ መዳረሻ',
    'login.sellerTitle': 'የሻጭ እና ሰራተኞች መግቢያ',
    'login.sellerSubtitle': 'የዕቃ ዝርዝር እና ትዕዛዝ አስተዳደር',
    'login.staffIdLabel': 'የሰራተኛ መታወቂያ ወይም ኢሜይል',
    'login.password': 'የይለፍ ቃል',
    'login.forgot': 'የይለፍ ቃል ረሱ?',
    'login.signIn': 'ግባ',
    'login.authenticating': 'በማረጋገጥ ላይ...',
    'login.needAccess': 'የሲስተም መዳረሻ ይፈልጋሉ?',
    'login.contactAdmin': 'አስተዳዳሪ ያነጋግሩ',
    'login.switch': 'የሂሳብ አይነት ይቀይሩ',
    'login.buyerTitle': 'የችርቻሮ አጋር መግቢያ',
    'login.buyerSubtitle': 'ምርቶችን ለማየት እና ትዕዛዞችን ለመላክ ወደ ዳሽቦርድ ይግቡ',
    'login.buyerIdLabel': 'የገዢ መታወቂያ ወይም ኢሜይል',
    'login.trouble': 'መግባት ተቸግረዋል?',
    'login.faq': 'ጥያቄዎች',
    'login.support': 'ድጋፍ',

    // Buyer Dashboard
    'buyer.welcome': 'እንኳን በደህና መጡ',
    'buyer.overview': 'ማጠቃለያ',
    'buyer.activeOrders': 'ንቁ ትዕዛዞች',
    'buyer.loyaltyTier': 'የአጋርነት ደረጃ',
    'buyer.monthlyOrders': 'የወርሃዊ ትዕዛዞች',
    'buyer.monthlySpend': 'የወርሃዊ ወጪ',
    'buyer.totalSpend': 'ጠቅላላ ወጪ',
    'buyer.recentOrders': 'የቅርብ ጊዜ ትዕዛዞች',
    'buyer.viewHistory': 'ታሪክ ይመልከቱ',
    'buyer.recommended': 'ለእርስዎ የተመረጡ',
    'buyer.seeAll': 'ሁሉንም ምርቶች ይመልከቱ',
    'buyer.add': 'ጨምር',
    'buyer.noOrders': 'ምንም ትዕዛዞች የሉም',

    // Buyer Common
    'buyer.cart': 'ጋሪ',
    'buyer.items': 'ዕቃዎች',
    'buyer.subtotal': 'ንዑስ ድምር',
    'buyer.tax': 'ታክስ',
    'buyer.total': 'ጠቅላላ',
    'buyer.placeOrder': 'ትዕዛዝ ይላኩ',
    'buyer.saveDraft': 'እንደ ረቂቅ አስቀምጥ',
    'buyer.search': 'ምርቶችን ይፈልጉ...',
    'buyer.soldOut': 'አልቋል',
    'buyer.lowStock': 'ዝቅተኛ ክምችት',
    'buyer.inStock': 'በመጋዘን ውስጥ',
    'buyer.pay': 'ክፈል',
    'buyer.invoice': 'ደረሰኝ',
    'buyer.makePayment': 'ክፍያ ፈጽም',
    'buyer.requestCredit': 'ብድር ይጠይቁ',
    'buyer.reorder': 'እንደገና እዘዝ',
    'buyer.cancelOrder': 'ትዕዛዝ ሰርዝ',
    'buyer.deleteOrder': 'ትዕዛዝ አጥፋ',
    'buyer.editDraft': 'ረቂቅ አርም',
    'buyer.notifications': 'ማሳወቂያዎች',

    // Orders Management
    'status.all': 'ሁሉም ትዕዛዞች',
    'status.draft': 'ረቂቅ',
    'status.on_review': 'በግምገማ ላይ',
    'status.pending': 'በመጠባበቅ ላይ',
    'status.processing': 'በሂደት ላይ',
    'status.shipped': 'ተልኳል',
    'status.delivered': 'ደርሷል',
    'status.undelivered': 'አልደረሰም',
    'status.cancelled': 'ተሰርዟል',
    'status.deleted': 'ተወግዷል',
    'order.new': 'አዲስ ትዕዛዝ',
    'order.process': 'ማቀናበር',
    'order.verify': 'አረጋግጥ',
    'order.submit': 'አስገባ',
    'order.fulfill': 'ትዕዛዝ ማሟላት',
    'order.markDelivered': 'እንደደረሰ ምልክት ያድርጉ',
    'order.lifecycle': 'የትዕዛዝ ሂደት',
    'order.partner': 'ገዢ አጋር',
    'order.manifest': 'የዕቃዎች ዝርዝር',
    'order.timeline': 'የኦዲት ጊዜ መስመር',
    'order.cancel': 'ሰርዝ',
    'order.invoice': 'ደረሰኝ',
    'order.edit': 'ትዕዛዝ አርም',
    'order.undelivered': 'አልደረሰም',
    'order.wholesaleValue': 'የጅምላ ዋጋ',
    'order.notFound': 'ትዕዛዝ አልተገኘም።',
    'order.cancelledBySeller': 'በሻጭ ተሰርዟል',
    'order.confirmedDelivered': 'ትዕዛዝ በመስክ ሰራተኞች መድረሱ ተረጋግጧል',
    'order.deliveryConfirmMessage': 'ይህ የትዕዛዙን ሁኔታ ወደ ደርሷል ያዘምናል። ገዢው ዕቃዎቹን በጥሩ ሁኔታ መቀበሉን ያረጋግጡ።',
    'order.stockRestock': 'አክሲዮን የሚሞላ:',
    'order.autoRestock': 'አክሲዮን በራስ-ሰር ይሞላል',
    'order.stopFulfillment': 'የማሟላት ሂደትን ያቆማል',
    'order.softDelete': 'ለስላሳ ስረዛ ፕሮቶኮል',
    'order.confirmHandover': 'ስኬታማ ርክክብን ያረጋግጡ',

    // Products Management
    'cat.all': 'ሁሉም',
    'loc.all': 'ሁሉም ቦታዎች',
    'loc.warehouse': 'መጋዘን',
    'loc.backroom': 'የኋላ ክፍል',
    'loc.showroom': 'ማሳያ ክፍል',
    'prod.add': 'አዲስ ምርት',
    'prod.restock': 'አክሲዮን ሙላ',
    'prod.editMode': 'ማስተካከያ',
    'prod.discard': 'ተው',
    'prod.saveChanges': 'ለውጦችን አስቀምጥ',
    'prod.delete': 'ምርት አጥፋ',
    'prod.modify': 'ምርት አስተካክል',
    'prod.restockUnits': 'አሃዶችን ሙላ',
    'prod.fulfillmentStock': 'የክምችት ደረጃ',
    'prod.catalogAttributes': 'የካታሎግ ዝርዝሮች',
    'prod.brand': 'ብራንድ',
    'prod.category': 'ምድብ',
    'prod.cost': 'የወጪ ዋጋ',
    'prod.sellingPrice': 'የመሸጫ ዋጋ',
    'prod.description': 'መግለጫ',
    'prod.reorderPoint': 'እንደገና ማዘዣ ነጥብ',
    'prod.status': 'ሁኔታ',
    'prod.wholesale': 'የጅምላ ሽያጭ',
    'prod.units': 'አሃዶች',
    'prod.noMatch': 'ምንም ተዛማጅ ምርቶች አልተገኙም',
    'prod.notFound': 'ምርት አልተገኘም',
    'prod.updated': 'የምርት ካታሎግ በተሳካ ሁኔታ ተዘምኗል።',
    'prod.deleteConfirm': 'እርግጠኛ ነዎት በቋሚነት መሰረዝ ይፈልጋሉ',
    'prod.supplierName': 'አቅራቢ ስም',
    'prod.supplierPhone': 'አቅራቢ ስልክ',

    // Common Actions & Labels
    'common.add': 'ጨምር',
    'common.edit': 'አስተካክል',
    'common.delete': 'አጥፋ',
    'common.save': 'አስቀምጥ',
    'common.cancel': 'ሰርዝ',
    'common.submit': 'ላክ',
    'common.back': 'ተመለስ',
    'common.confirm': 'አረጋግጥ',
    'common.view': 'ተመልከት',
    'common.status': 'ሁኔታ',
    'common.date': 'ቀን',
    'common.search': 'ፈልግ...',
    'logout': 'ውጣ',
    'common.id': 'መለያ',
    'common.buyer': 'ገዢ',
    'common.revenue': 'ገቢ',
    'common.accountId': 'የሂሳብ መታወቂያ',
    'common.sku': 'መለያ ቁጥር',
    'common.loading': 'በመጫን ላይ...',
    'common.upload': 'ጫን',
    'common.reasonRequired': 'እባክዎ ምክንያት ያቅርቡ።',
    'common.deletionReason': 'የመሰረዝ ምክንያት',
    'common.cancellationReason': 'የመሰረዝ ምክንያት',
    'common.deliveryFailureReason': 'ያለመድረስ ምክንያት',
    'common.internalNotes': 'የውስጥ ማስታወሻዎች',
    'common.actions': 'እርምጃዎች',
    'common.noRecords': 'ምንም መዝገቦች አልተገኙም',
    'common.discardChanges': 'ለውጦችን ተው',
    'common.saveUpdates': 'ዝማኔዎችን አስቀምጥ',
    'common.activate': 'አግብር',
    'common.deactivate': 'አቦዝን',
    'common.editProfile': 'መገለጫ አርትዕ',
    'common.cancelEdit': 'አርትዖት ሰርዝ',
    'common.item': 'ዕቃ',
    'common.type': 'ዓይነት',
    'common.quantity': 'ብዛት',
    'common.reason': 'ምክንያት',
    'common.resolution': 'ውሳኔ',

    // Analytics
    'reports.title': 'ሪፖርቶች',
    'reports.subtitle': 'ለጅምላ ንግድዎ የአፈጻጸም ማጠቃለያዎች',
    'reports.revenueTrend': 'የገቢ አፈጻጸም',
    'reports.revenueTrendDesc': 'ከተገኘው የትዕዛዝ ታሪክ የተመሠረተ የገቢ አዝማሚያ።',
    'reports.topTrendsDesc': 'በቅርብ የንጽጽር ጊዜ መስኮት ውስጥ ምርጥ አፈጻጸም ያሳዩ ምርቶች።',
    'analytics.title': 'ትንተና',
    'analytics.subtitle': 'ለጅምላ ፍላጎት ትንበያ እና ሁኔታ ማሰስ',
    'analytics.viewScope': 'የእይታ ክልል',
    'analytics.salesGrowth': 'የሽያጭ እድገት',
    'analytics.vsPrevious': 'ካለፈው ጋር',
    'analytics.totalRevenue': 'ጠቅላላ ገቢ',
    'analytics.allTime': 'ሁልጊዜ',
    'analytics.inventoryTurnover': 'የክምችት ልውውጥ',
    'analytics.efficiencyScore': 'ብቃት',
    'analytics.demandForecast': 'የፍላጎት ትንበያ',
    'analytics.historical': 'ታሪካዊ',
    'analytics.forecasted': 'ተንብዮአል',
    'analytics.scenarioTitle': 'ሁኔታ ሞዴሊንግ',
    'analytics.scenarioDesc': 'ለውጫዊ የሽያጭ ውሂብ CSV ይጫኑ።',
    'analytics.uploadCsv': 'CSV ጫን',
    'analytics.changeFile': 'ፋይል ቀይር',
    'analytics.clearData': 'ውሂብ አጽዳ',
    'analytics.dropCsv': 'CSV እዚህ ይጣሉ',
    'analytics.csvFormat': 'ቅርጸት፡ ቀን (ዓምድ 1)፣ ሽያጭ (ዓምድ 2)',
    'analytics.topTrends': 'ዋና የምርት አዝማሚያዎች',
    'analytics.recentVsPrev': 'የቅርብ vs ያለፈው',
    'analytics.noData': 'ምንም የሽያጭ መረጃ የለም።',
    'analytics.lastMonth': 'ካለፈው ወር',

    // Returns
    'returns.financialImpact': 'የገንዘብ ተጽዕኖ',
    'returns.financialImpactDesc': 'በጉዳት እና ማስወገድ የጠፋ ዋጋ',
    'returns.operationalPulse': 'የአሠራር ምት',
    'returns.operationalPulseDesc': 'በዚህ ወር የተመዘገቡ ክስተቶች',
    'returns.recoveryRate': 'የመልሶ ማግኛ መጠን',
    'returns.recoveryRateDesc': 'ወደ ክምችት የተመለሱ ዕቃዎች በመቶኛ',
    'returns.reasonDistribution': 'የክስተት ምክንያት ስርጭት',
    'returns.recentLog': 'የቅርብ ጊዜ ክስተት ምዝግብ ማስታወሻ',
    'returns.addLog': 'ምዝግብ ማስታወሻ አክል',
    'returns.noIncidents': 'ምንም ክስተቶች አልተመዘገቡም',
    'returns.supplierWatch': 'የአቅራቢ ጥለት እይታ',
    'returns.riskScore': 'የስጋት ነጥብ',
    'returns.packagingFault': 'የማሸጊያ ስህተት ተገኝቷል',
    'returns.globalPattern': 'ዓለም አቀፍ ጥለት ፍለጋ',
    'returns.logTitle': 'የምርት ክስተት ይመዝግቡ',
    'returns.logDesc': 'ጉዳት ወይም የደንበኛ ተመላሽ ይመዝግቡ።',
    'returns.itemInfo': 'የዕቃ መረጃ',
    'returns.selectProduct': 'ምርት ይምረጡ',
    'returns.chooseProduct': 'ምርት ይምረጡ...',
    'returns.incidentType': 'የክስተት ዓይነት',
    'returns.unitsAffected': 'የተጎዱ አሃዶች',
    'returns.triggerReason': 'ምክንያት',
    'returns.fulfillmentRes': 'የማሟላት ውሳኔ',
    'returns.resRestock': 'ወደ መጋዘን መልስ',
    'returns.resDisposal': 'ለማስወገድ ምልክት ያድርጉ',
    'returns.resReturn': 'ወደ አምራች መልስ',
    'returns.completeLog': 'ምዝገባውን ጨርስ',

    // Credits
    'credits.title': 'የብድር አስተዳደር',
    'credits.subtitle': 'የተመላሽ ጥያቄዎችን ይገምግሙ።',
    'credits.logRequest': 'የብድር ጥያቄ ይመዝግቡ',
    'credits.pendingApproval': 'በመጠባበቅ ላይ',
    'credits.creditsIssued': 'የተሰጡ ብድሮች (ጠቅላላ)',
    'credits.reqId': 'የጥያቄ መለያ',
    'credits.assocOrder': 'ተዛማጅ ትዕዛዝ',
    'credits.requested': 'የተጠየቀ',
    'credits.approved': 'ጸድቋል',
    'credits.generalCredit': 'አጠቃላይ ብድር',
    'credits.noRequests': 'ምንም የብድር ጥያቄዎች አልተገኙም',
    'credits.logTitle': 'የብድር ማስታወሻ ይስጡ',
    'credits.logDesc': 'የተመላሽ ገንዘብ ወይም የሂሳብ ብድር ጥያቄ ይመዝግቡ።',
    'credits.accountDetails': 'የሂሳብ ዝርዝሮች',
    'credits.selectBuyer': 'የገዢ ሂሳብ ይምረጡ',
    'credits.chooseBuyer': 'ገዢ ይምረጡ...',
    'credits.assocOrderOpt': 'ተዛማጅ ትዕዛዝ (አማራጭ)',
    'credits.generalCreditOpt': 'አጠቃላይ ብድር (የተለየ ትዕዛዝ የለም)',
    'credits.creditTerms': 'የብድር ውሎች',
    'credits.creditAmount': 'የብድር መጠን (ETB)',
    'credits.reasonCode': 'ምክንያት ኮድ',
    'credits.notesPlaceholder': 'ለማጽደቅ ዝርዝሮች...',
    'credits.submitRequest': 'ጥያቄ አቅርብ',

    // Payments
    'payments.title': 'ክፍያዎች',
    'payments.proof': 'የክፍያ ማረጋገጫ',
    'payments.viewProof': 'ሙሉ ምስል ይመልከቱ',
    'payments.verification': 'የማረጋገጫ ዝርዝሮች',
    'payments.expected': 'የሚጠበቀው መጠን',
    'payments.reported': 'የተዘገበው መጠን',
    'payments.reference': 'የማጣቀሻ መለያ',
    'payments.submissionTime': 'የገባበት ሰዓት',
    'payments.mismatch': 'የመጠን አለመመጣጠን',
    'payments.mismatchDesc': 'የተዘገበው የክፍያ መጠን ከጠቅላላው የትዕዛዝ ዋጋ ጋር አይዛመድም። እባክዎ ከማጽደቅዎ በፊት ያረጋግጡ።',
    'payments.reviewNotes': 'የግምገማ ማስታወሻዎች',
    'payments.reviewNotesPlaceholder': 'የመከልከል ወይም ልዩ ማስታወሻዎችን ያክሉ...',
    'payments.reject': 'ከልክል',
    'payments.markMismatch': 'አልተዛመደም',
    'payments.approve': 'አጽድቅ',
    'payments.noPayments': 'ለዚህ ማጣሪያ ምንም ክፍያዎች አልተገኙም',
    'status.pending_review': 'በመገምገም ላይ',
    'status.approved': 'ጸድቋል',
    'status.rejected': 'ተከልክሏል',
    'status.mismatched': 'አልተዛመደም',

    // Alerts
    'alerts.title': 'ዝቅተኛ የአክሲዮን ማስጠንቀቂያዎች',
    'alerts.subtitle': 'ወዲያውኑ መሞላት የሚያስፈልጋቸው ዕቃዎች።',
    'alerts.bulkRestock': 'በጅምላ ሙላ',
    'alerts.quickRestock': 'ፈጣን ሙላ',
    'alerts.allStocked': 'ሁሉም ተሞልቷል!',
    'alerts.allStockedDesc': 'በአሁኑ ጊዜ ዝቅተኛ ክምችት ያላቸው ምርቶች የሉም።',
    'alerts.browseCatalog': 'ካታሎግ አስስ',

    // Buyers
    'buyers.title': 'የጅምላ አጋሮች',
    'buyers.subtitle': 'የተመዘገቡ ሂሳቦች',
    'buyers.newBuyer': 'አዲስ ገዢ',
    'buyers.searchPlaceholder': 'ሂሳቦችን በስም፣ መታወቂያ ወይም አድራሻ ይፈልጉ...',
    'buyers.perk': 'ጥቅማ ጥቅም',
    'buyers.noMatch': 'ከፍለጋዎ ጋር የሚዛመዱ ሂሳቦች የሉም',
    'buyers.notFound': 'ገዢ አልተገኘም።',
    'buyers.member': 'አባል',
    'buyers.lifetimeSpend': 'ጠቅላላ ወጪ',
    'buyers.orderCount': 'የትዕዛዝ ብዛት',
    'buyers.pricingPerk': 'የዋጋ ጥቅም',
    'buyers.accountState': 'የሂሳብ ሁኔታ',
    'buyers.modifyIdentity': 'ማንነት አስተካክል',
    'buyers.businessInfo': 'የንግድ መረጃ',
    'buyers.companyName': 'የድርጅት ህጋዊ ስም',
    'buyers.contactManager': 'አግኙን ስራ አስኪያጅ',
    'buyers.businessPhone': 'የንግድ ስልክ',
    'buyers.primaryEmail': 'ዋና ኢሜይል አድራሻ',
    'buyers.deliveryPoint': 'ዋና የመላኪያ ነጥብ',
    'buyers.legalName': 'ህጋዊ ስም',
    'buyers.primaryContact': 'ዋና የመገናኛ ነጥብ',
    'buyers.businessEmail': 'የንግድ ኢሜይል',
    'buyers.regPhone': 'የተመዘገበ ስልክ',
    'buyers.fulfillmentTerminal': 'የማሟያ ተርሚናል',
    'buyers.partnerTier': 'የአጋር ደረጃ እና ጥቅሞች',
    'buyers.off': 'ቅናሽ',
    'buyers.operationalLog': 'የአሠራር መዝገብ',
    'buyers.fullHistory': 'ሙሉ ታሪክ',

    // Logs
    'logs.title': 'የሲስተም ኦዲት መዝገብ',
    'logs.eventsRecorded': 'ክስተቶች ተመዝግበዋል',
    'logs.refresh': 'መዝገቦችን ያድሱ',
    'logs.searchPlaceholder': 'መዝገቦችን በድርጊት፣ ተጠቃሚ ወይም ዝርዝሮች ይፈልጉ...',
    'logs.noLogs': 'ከመስፈርትዎ ጋር የሚዛመዱ መዝገቦች የሉም',
    'log.module.all': 'ሁሉም',
    'log.module.orders': 'ትዕዛዞች',
    'log.module.inventory': 'ክምችት',
    'log.module.finance': 'ፋይናንስ',
    'log.module.users': 'ተጠቃሚዎች',
    'log.module.settings': 'ቅንብሮች',

    // Pricing
    'pricing.title': 'የዋጋ ስትራቴጂ',
    'pricing.subtitle': 'ባለብዙ ደረጃ ቅናሽ ሞተር',
    'pricing.newTier': 'አዲስ ደረጃ',
    'pricing.newVolume': 'አዲስ የብዛት ደረጃ',
    'pricing.newConstraint': 'አዲስ ገደብ',
    'pricing.tiers': 'የታማኝነት ደረጃዎች',
    'pricing.bulk': 'የጅምላ ብዛት',
    'pricing.margin': 'የትርፍ ጥበቃ',
    'pricing.gifted': 'ዒላማዎች ሲደርሱ የሚሰጥ',
    'pricing.minSpend': 'ወጪ',
    'pricing.tenure': 'ቆይታ',
    'pricing.bulkTitle': 'ዓለም አቀፍ የብዛት ገደቦች',
    'pricing.bulkDesc': 'ብዛቶች ሲሟሉ በራስ-ሰር የሚደረግ ቅናሽ።',
    'pricing.newVolumeStep': 'አዲስ የብዛት ደረጃ ይግለጹ',
    'pricing.marginTitle': 'የትርፍ ጥበቃ ሎጂክ',
    'pricing.marginDesc': 'ከፍተኛ ትርፍ ላላቸው ዕቃዎች በራስ-ሰር ማበረታቻ ይሰጣል። የምርት ዋጋ እና የትርፍ ህዳግ መስፈርቱን ካሟላ ለገዢው ተጨማሪ ቅናሽ ይሰጣል።',
    'pricing.trigger': 'የመቀስቀሻ ሁኔታ',
    'pricing.incentive': 'ማበረታቻ',
    'pricing.addConstraint': 'ገደብ ያክሉ',
    'pricing.bonus': 'ቦነስ',

    // Staff
    'staff.title': 'የቡድን አባላት',
    'staff.activeAccounts': 'ንቁ መለያዎች',
    'staff.newStaff': 'አዲስ ሰራተኛ',
    'staff.search': 'የቡድን አባላትን በስም፣ ሚና ወይም ኢሜይል ይፈልጉ...',
    'staff.noMatch': 'ከፍለጋዎ ጋር የሚዛመዱ የቡድን አባላት የሉም',

    // Roles
    'roles.title': 'የፍቃድ ሚናዎች',
    'roles.profiles': 'የመዳረሻ መገለጫዎች',
    'roles.new': 'አዲስ ሚና',
    'roles.search': 'ሚናዎችን በስም፣ ደረጃ ወይም ችሎታ ይፈልጉ...',
    'roles.members': 'አባላት',
    'roles.activeModules': 'ንቁ ሞጁሎች',
    'roles.globalScope': 'ዓለም አቀፍ ሽፋን',
    'roles.systemWide': 'በስርዓቱ በሙሉ',
    'roles.restricted': 'የተገደበ',
    'roles.noMatch': 'ከፍለጋዎ ጋር የሚዛመዱ ሚናዎች የሉም',
    'roles.more': 'ተጨማሪ',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const getStoredLanguage = (): Language => {
    // Check for authenticated user preference first
    const userId = localStorage.getItem('userId');
    if (userId) {
        const userPref = localStorage.getItem(`language_${userId}`);
        if (userPref === 'en' || userPref === 'am') return userPref;
    }
    
    // Fallback to global setting (e.g. set on login screen)
    const globalPref = localStorage.getItem('language');
    if (globalPref === 'en' || globalPref === 'am') return globalPref;
    
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(getStoredLanguage());

  // Listen for auth changes to switch language context
  useEffect(() => {
    const handleAuthChange = () => {
        setLanguageState(getStoredLanguage());
    };
    window.addEventListener('auth-change', handleAuthChange);
    return () => window.removeEventListener('auth-change', handleAuthChange);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const userId = localStorage.getItem('userId');
    if (userId) {
        // Save for specific user
        localStorage.setItem(`language_${userId}`, lang);
    } else {
        // Save globally (for login screens)
        localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
